/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace DoctorStore {
      
    export type DoctorStruct = {id: BigNumberish, name: string, specialty: string, experience: string, fee: BigNumberish, available: boolean, timestamp: BigNumberish}

    export type DoctorStructOutput = [id: bigint, name: string, specialty: string, experience: string, fee: bigint, available: boolean, timestamp: bigint] & {id: bigint, name: string, specialty: string, experience: string, fee: bigint, available: boolean, timestamp: bigint }
  
    }

  export interface DoctorStoreInterface extends Interface {
    getFunction(nameOrSignature: "doctorCount" | "doctors" | "getAllDoctors" | "getCount" | "getDoctor" | "owner" | "registerDoctor" | "setAvailability"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DoctorRegistered" | "DoctorUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'doctorCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'doctors', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllDoctors', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDoctor', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerDoctor', values: [string, string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setAvailability', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'doctorCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'doctors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllDoctors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAvailability', data: BytesLike): Result;
  }

  
    export namespace DoctorRegisteredEvent {
      export type InputTuple = [id: BigNumberish, name: string, specialty: string, fee: BigNumberish];
      export type OutputTuple = [id: bigint, name: string, specialty: string, fee: bigint];
      export interface OutputObject {id: bigint, name: string, specialty: string, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DoctorUpdatedEvent {
      export type InputTuple = [id: BigNumberish, available: boolean];
      export type OutputTuple = [id: bigint, available: boolean];
      export interface OutputObject {id: bigint, available: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DoctorStore extends BaseContract {
    
    connect(runner?: ContractRunner | null): DoctorStore;
    waitForDeployment(): Promise<this>;

    interface: DoctorStoreInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    doctorCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    doctors: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, boolean, bigint] & {id: bigint, name: string, specialty: string, experience: string, fee: bigint, available: boolean, timestamp: bigint }],
      'view'
    >
    

    
    getAllDoctors: TypedContractMethod<
      [],
      [DoctorStore.DoctorStructOutput[]],
      'view'
    >
    

    
    getCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getDoctor: TypedContractMethod<
      [_id: BigNumberish, ],
      [DoctorStore.DoctorStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerDoctor: TypedContractMethod<
      [_name: string, _specialty: string, _experience: string, _fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setAvailability: TypedContractMethod<
      [_id: BigNumberish, _available: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'doctorCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'doctors'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, boolean, bigint] & {id: bigint, name: string, specialty: string, experience: string, fee: bigint, available: boolean, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getAllDoctors'): TypedContractMethod<
      [],
      [DoctorStore.DoctorStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDoctor'): TypedContractMethod<
      [_id: BigNumberish, ],
      [DoctorStore.DoctorStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerDoctor'): TypedContractMethod<
      [_name: string, _specialty: string, _experience: string, _fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAvailability'): TypedContractMethod<
      [_id: BigNumberish, _available: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DoctorRegistered'): TypedContractEvent<DoctorRegisteredEvent.InputTuple, DoctorRegisteredEvent.OutputTuple, DoctorRegisteredEvent.OutputObject>;
getEvent(key: 'DoctorUpdated'): TypedContractEvent<DoctorUpdatedEvent.InputTuple, DoctorUpdatedEvent.OutputTuple, DoctorUpdatedEvent.OutputObject>;

    filters: {
      
      'DoctorRegistered(uint256,string,string,uint256)': TypedContractEvent<DoctorRegisteredEvent.InputTuple, DoctorRegisteredEvent.OutputTuple, DoctorRegisteredEvent.OutputObject>;
      DoctorRegistered: TypedContractEvent<DoctorRegisteredEvent.InputTuple, DoctorRegisteredEvent.OutputTuple, DoctorRegisteredEvent.OutputObject>;
    

      'DoctorUpdated(uint256,bool)': TypedContractEvent<DoctorUpdatedEvent.InputTuple, DoctorUpdatedEvent.OutputTuple, DoctorUpdatedEvent.OutputObject>;
      DoctorUpdated: TypedContractEvent<DoctorUpdatedEvent.InputTuple, DoctorUpdatedEvent.OutputTuple, DoctorUpdatedEvent.OutputObject>;
    
    };
  }