/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DoctorStore } from './DoctorStore.js';
export * as factories from './factories/index.js';
export { DoctorStore__factory } from './factories/DoctorStore__factory.js';